sudo: required

language: go

go:
  - 1.9.3

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

before_script:
    - go get github.com/Masterminds/glide
    - glide install

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - make
  - make test

# In Travis, we need to bind to 127.0.0.1 in order to get a working connection. This environment variable
# tells dockertest to do that.
env:
  - DOCKERTEST_BIND_LOCALHOST=true
